### ISSUE TITLE
Unable to build on Windows 10, VS 14

### ISSUE THREAD

**Issue by thomasaarholt** [Marcello-Sega/pytetgen#3]
I'm getting a rather large error when trying to build this by `pip install pytetgen` on python 3.8, windows 10 and Visual Studio 14. Cython is installed.

I'm specifically looking for a drop-in replacement of scipy's Delaunay function for use with the scipy point cloud interpolation functions (`LinearNDInterpolator` and similar). Just in case you have any ideas :)

The [full error log is here](https://gist.github.com/thomasaarholt/34f5712b07b5bee119d649808961f37c), should you be interested.

**Comment by Marcello-Sega** [comment]
Hi, 

I never tested it on a window machine, but from the error messages it looks like it might be a cython problem. Could you try updating your cython? 

M

**Comment by thomasaarholt** [comment]
I'd originally installed it from conda today, and tried uninstalling and reinstalling it using pip, but I get the same error.

**Comment by Marcello-Sega** [comment]
Mhhh... I'm using py3.6 on my machine. I will have it tested on travis and will let you know asap.

**Comment by Marcello-Sega** [comment]
Bad luck:
```
Worker information

The language 'python' is currently unsupported on the Windows Build Environment.

```

I'll try something else.

**Comment by Marcello-Sega** [comment]
Still haven't managed to try it on a windows machine, but now it behaves well with python3.x. 
The old implementation had a problem with the GIL and memory management.

Could you try upgrading with `pip install --upgrade pytetgen` ?  The new version should be 0.2.0

Most likely the problem was the old .cpp source included in the package, which was definitely not compatible with python3.x. Another option, if still it does not work, would be to install from source to generate the .cpp source from .pyx directly on your machine ( `pip install  --compile  . ` from within the source directory)

**Comment by thomasaarholt** [comment]
Yes! That built and installed!

**Comment by thomasaarholt** [comment]
Wahey! And it's twice as fast as scipy's implementation on my computer!

**Comment by thomasaarholt** [comment]
That was for 1 million 2D points:

```python
import numpy as np
points = np.random.random((1000000, 2)) * (1000, 1000) # spread over 0-1000 bc we could run into floating point errors

import pytetgen
from scipy.spatial import Delaunay
%timeit Delaunay(points)
%timeit pytetgen.Delaunay(points)

6.34 s ± 20.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.04 s ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by Marcello-Sega** [comment]
I guess this can be closed.
